POST https://acrateapp-backend-dev-tnzm.2.ie-1.fl0.io/api/courses
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MTEwMDQwMjYwNCwiaWQiOiI2NTM5M2JlZmNkYmEyMGVhYTE2ZTU5OWUiLCJpYXQiOjE2OTgyNDk3NDJ9.Gez37xLDIV0i7FI7ev2RmkwlvR60bx8SU3LgoGDLqx0

{
  "nombre": "ESTADISTICA II",
  "semestre": 8,
  "nombre_profesor": "RANGEL MANCHEGO EDER DAVID",
  "aula": "B006",
  "nota_corte_1": 3.0,
  "nota_corte_2": 4.0,
  "horario": {
    "dia": "Lunes",
    "horainicio": "14:15PM",
    "horafin": "15:45"
  },
  "programacion_parciales": {
    "parcial_1": "2023-09-18",
    "parcial_2": "2023-11-20"
  }
}



