POST http://localhost:3003/api/courses
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MTAwMTA2NTgzMiwiaWQiOiI2NTM1NzkyNjU3MWY4OTllMGFmNTFhM2UiLCJpYXQiOjE2OTgwMDMyNDZ9.IMKSj3naC-zm8EYJm30kKHNfcvQmc36f9po0hHfMNN8

{
  "nombre": "Emprendimiento",
  "semestre": 8,
  "nombre_profesor": "Anibal Lopez",
  "aula": "B007",
  "nota_corte_1": 4.8,
  "nota_corte_2": 4.8,
  "horario": {
    "dia": "Lunes",
    "horainicio": "10:45",
    "horafin": "12:15"
  },
  "programacion_parciales": {
    "parcial_1": "2023-09-11",
    "parcial_2": "2023-11-13"
  }
}



