POST https://acrateapp-backend-dev-tnzm.2.ie-1.fl0.io/api/login
Content-Type: application/json

{
  "username": "1001065832",
  "password": "1001065832"
}

###
POST https://backend-acrateapp.onrender.com/api/login
Content-Type: application/json

{
  "username": "1001065832",
  "password": "1001065832"
}

# {
#   "username": "1100402604",
#   "password": "1100402604"
# }