# POST https://acrateapp-backend-dev-tnzm.2.ie-1.fl0.io/api/user
POST http://localhost:3003/api/user
Content-Type: application/json

{
  "username": 1100402606,
  "name": "Luis Bustamante",
  "password": "1100402606",
  "codigo_estudiantil": "023562087",
  "facultad": "Facultad Ciencias de la Ingeniería",
  "carrera": "Ingeniería en Sistemas"
}